### ISSUE TITLE
Add Regeneration outside ship secondary values

### ISSUE THREAD

**Issue by CroSSinski** [Toskan4134/LethalRegeneration#2]
Sorry for putting this here, idk why i cant create request, im not familiar with github. Anyway can you consider adding regeneration outside second values?

I mean if you set Yes for Regeneration outside ship then you can set (an example)

Regeneration outside ship value: 2
Regeneration outside ship tick: 2

full example:

Regen Power: 5
Tick per Regen: 2
Regen outside ship: True
Regen outside ship value: 2
Regen outside ship per tick: 2

**Comment by Toskan4134** [comment]
Good Request, I will consider adding it
